apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-prod

resources:
  - ../base
  - namespace.yaml

images:
  - name: weather-app
    newName: replace-with-acr-name.azurecr.io/weather-app
    newTag: prod

replicas:
  - name: weather-app
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: weather-app-config
    patch: |-
      - op: replace
        path: /data/REDIS_HOST
        value: replace-with-prod-redis-hostname
