apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    app.kubernetes.io/name: weather-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: weather-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
